webshop/Models/WKorb.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Web;
using System.Web.DynamicData;
using System.Web.Script.Serialization;

namespace webshop.Models
{
    public class WKorb
    {
        public string Rolle { get; set; }
        public List<WKorbItem> warenkorb { get; set; }

        public WKorb()
        {
            var cname = "wkorb";
            var cookie = HttpContext.Current.Request.Cookies.Get(cname);
            if (cookie != null)
            {
                var json = cookie.Value;
                if (!string.IsNullOrEmpty(json) && !json.Equals("[]"))
                {
                    warenkorb = System.Web.Helpers.Json.Decode<List<WKorbItem>>(json);
                }
            }
            else
            {
                warenkorb = new List<WKorbItem>();
            }
        }

        public WKorb(List<WKorbItem> warenkorb,string role)
        {
            this.warenkorb = warenkorb;
            this.Rolle = role;
        }

        public void AddToCart(WKorbItem produkt)
        {
            if (!warenkorb.Contains(produkt))
            {
                warenkorb.Add(produkt);
            }
            else
            {
                var item = warenkorb.First(x => x.ProduktId == produkt.ProduktId);
                item.Anzahl += produkt.Anzahl;
            }
        }

        public bool IstVorhanden()
        {
            return HttpContext.Current.Request.Cookies.Get("wkorb") != null;
        }

        public int GetAnzahlElemente()
        {
            return warenkorb.Sum(x => x.Anzahl);
        }

        public decimal GetSumme()
        {
            return warenkorb.Sum(x => x.Preis(Rolle));
        }


        [Serializable]
        public class WKorbItem
        {
            public int ProduktId { get; set; }
            public string ProduktName { get; set; }

            [Required(ErrorMessage = "Anzahl muss angegeben werden!")]
            [Range(1, int.MaxValue)]
            public int Anzahl { get; set; }

            public decimal Preis(string role)
            {
                return _unitPrice(role)*Anzahl;
            }

            private decimal _unitPrice(string role)
            {
                return Produkt.GetPreis(ProduktId, role);
            }

            public WKorbItem(int ProduktId, int Anzahl, string role)
            {
                this.ProduktId = ProduktId;
                this.Anzahl = Anzahl;
                var p = Produkt.GetProduktDetails(ProduktId, role);
                this.ProduktName = p.Name;
            }

            public WKorbItem()
            {
                ProduktId = -1;
                ProduktName = "";
                Anzahl = 0;
            }

            public bool Equals(WKorbItem other)
            {
                if (other == null)
                    return false;
                return this.ProduktId == other.ProduktId;
            }

            public override bool Equals(Object obj)
            {
                if (obj == null)
                    return false;
                return Equals(obj as WKorbItem);
            }
        }
    }
}

webshop/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using webshop.Models;

namespace webshop.Controllers
{
    public class AdminController : Controller
    {
        public ActionResult Index()
        {
            if (Session["authenticatedBE"] == null || Session["authenticatedBE"].Equals(""))
                return RedirectToAction("Login");
            var list = Nutzer.GetLastLoggedIn();
            return View(list);
        }

        public ActionResult Register()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Login l)
        {
            if (ModelState.IsValid)
            {
                if (l.LoginCheckBE())
                {
                    Session["authenticatedBE"] = l.Id;
                    return RedirectToAction("Index");
                }
                else
                {
                    Session["authenticatedBE"] = "";
                    ViewBag.ErrorMessage = "Login nicht erfolgreich.";
                    ViewBag.ErrorDescription = "falsche Kombination von Nutzername und Kennwort.";
                }
            }
            return View();
        }

        // GET: Register
        public ActionResult RegisterStudent()
        {
            return View();
        }

        public ActionResult RegisterMitarbeiter()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RegisterStudent(Student s)
        {
            if (ModelState.IsValid)
            {
                if (!FE_Nutzer.BereitsVorhanden(s.E_Mail1))
                {
                    s.Registrieren();
                    ModelState.Clear();
                    ViewBag.Success = s.Name + "wurde erfolgreich registriert.";
                }
                else
                {
                    ViewBag.ErrorMessage = "Registrieren fehlgeschlagen.";
                    ViewBag.ErrorDescription = "E-Mail bereits vorhanden.";
                }
            }
            return View();
        }


        [HttpPost]
        public ActionResult RegisterMitarbeiter(Mitarbeiter m)
        {
            if (ModelState.IsValid)
            {
                if (!FE_Nutzer.BereitsVorhanden(m.E_Mail1))
                {
                    m.Registrieren();
                    ModelState.Clear();
                    ViewBag.Success = m.Name + "wurde erfolgreich registriert.";
                }
                else
                {
                    ViewBag.ErrorMessage = "Registrieren fehlgeschlagen.";
                    ViewBag.ErrorDescription = "E-Mail bereits vorhanden.";
                }
            }
            return View();
        }
    }
}

webshop/Controllers/ProdukteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webshop.Models;
using webshop.Models.LINQ;

namespace webshop.Controllers
{
    public class ProdukteController : Controller
    {
        // GET: Produkte
        public ActionResult Index()
        {
            if (Session["authenticatedBE"] == null || Session["authenticatedBE"].Equals(""))
                return RedirectToAction("Login","Admin");
            var liste = Models.Produkt.GetByKategorie();
            if (liste == null)
            {
                liste = new List<Models.LINQ.Produkt>();
            }
            return View(liste);
        }

        // GET: Produkte/Create
        public ActionResult Create()
        {
            if (Session["authenticatedBE"] == null || Session["authenticatedBE"].Equals(""))
                return RedirectToAction("Login", "Admin");
            return View();
        }

        // POST: Produkte/Create
        [HttpPost]
        public ActionResult Create(Models.LINQ.Produkt pr)
        {
            if (ModelState.IsValid)
            {
                using (var p = new PraktikumDataContext())
                {
                    pr.FK_Kategorie = 1;
                    // insert produkt into db
                    p.Produkt.InsertOnSubmit(pr);
                    p.SubmitChanges();
                }

                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: Produkte/Edit/5
        public ActionResult Edit(int id=0)
        {
            if (Session["authenticatedBE"] == null || Session["authenticatedBE"].Equals(""))
                return RedirectToAction("Login", "Admin");
            string role = Session["role"] != null && string.IsNullOrEmpty(Session["role"].ToString())
                ? Session["role"].ToString()
                : "Gast";
            var p = new PraktikumDataContext();
            var produkt = p.Produkt.FirstOrDefault(x => x.ID == id);
            if (p != null)
            {
                return View(produkt);
            }
            return RedirectToAction("Index", "Produkte");
        }

        // POST: Produkte/Edit/5
        [HttpPost]
        public ActionResult Edit(Models.LINQ.Produkt pr)
        {
            if (ModelState.IsValid)
            {
                using (var p = new PraktikumDataContext())
                {
                    var query = p.Produkt.FirstOrDefault(x => x.ID == pr.ID);
                    query.Name = pr.Name;
                    query.Beschreibung = pr.Beschreibung;
                    if (pr.FK_Bild != null)
                    {
                        query.FK_Bild = pr.FK_Bild;
                        query.Bild = p.Bild.FirstOrDefault(x => x.ID == pr.FK_Bild.Value);
                    }
                    p.SubmitChanges();
                }

                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: Bilder/Delete/5
        public ActionResult Delete(int id)
        {
            if (Session["authenticatedBE"] == null || Session["authenticatedBE"].Equals(""))
                return RedirectToAction("Login", "Admin");
            var p = Models.Produkt.GetProduktDetails(id);
            if (p == null)
                return RedirectToAction("Index", "Produkte");
            return View(p);
        }

        // POST: Bilder/Delete/5
        [HttpPost]
        public ActionResult Delete(Models.LINQ.Produkt pr)
        {
            var p = new PraktikumDataContext();
            p.Produkt.DeleteOnSubmit(pr);
            p.SubmitChanges();
            return RedirectToAction("Index","Produkte");
        }
    }
}

webshop/Controllers/StartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using webshop.Models;
using webshop.Models.LINQ;
using Produkt = webshop.Models.Produkt;

namespace webshop.Controllers
{
    public class StartController : Controller
    {
        // GET: Start
        public ActionResult Index()
        {
            return View();
        }

        // GET: Details
        public ActionResult Details(int id = 0)
        {
            if (id == 0 || !Produkt.IsValidId(id))
            {
                return RedirectToAction("Produkte");
            }
            var p = Produkt.GetProduktDetails(id, (Session["role"] != null ? Session["role"].ToString() : ""));
            return View(p);
        }

        // GET: Produkte
        public ActionResult Produkte(string kategorieName = "")
        {
            var liste = Produkt.GetByKategorie(kategorieName);
            return View(liste);
        }

        private List<WKorb.WKorbItem> ReadFromCookie()
        {
            var cname = "wkorb";
            var cookie = HttpContext.Request.Cookies.Get(cname);
            List<WKorb.WKorbItem> wkorb = null;
            if (cookie != null)
            {
                var json = cookie.Value;
                // Liste nicht leer?
                if (!string.IsNullOrEmpty(json) && !json.Equals("[]"))
                {
                    wkorb = System.Web.Helpers.Json.Decode<List<WKorb.WKorbItem>>(json);
                }
            }
            return wkorb;
        }

        private void WriteToCookie(List<WKorb.WKorbItem> wkorb)
        {
            var cname = "wkorb";
            var cookie = HttpContext.Request.Cookies.Get(cname);
            // cookie vorhanden?
            if (cookie == null)
            {
                cookie = new HttpCookie(cname);
            }
            cookie.Value = System.Web.Helpers.Json.Encode(wkorb);
            cookie.Expires = DateTime.Now.AddHours(1);
            HttpContext.Response.SetCookie(cookie);
        }

        public ActionResult Wkorb()
        {
            var wkorb = ReadFromCookie();
            // wenn cookie nicht vorhanden
            if (wkorb == null)
            {
                wkorb = new List<WKorb.WKorbItem>();
            }
            return View(wkorb);
        }

        [HttpPost]
        public ActionResult Details(FormCollection form)
        {
            if (Session["authenticated"] == null || Session["authenticated"].Equals(""))
                return RedirectToAction("Index", "Login");
            var p = new WKorb.WKorbItem(form["produkt_id"].AsInt(), form["anzahl"].AsInt(), (Session["role"] != null ? Session["role"].ToString() : ""));
            var wkorb = ReadFromCookie();
            if (wkorb == null)
            {
                wkorb = new List<WKorb.WKorbItem>();
            }
            WKorb WKorbWrapper = new WKorb(wkorb, Session["role"] != null ? Session["role"].ToString() : "");
            WKorbWrapper.AddToCart(p);
            WriteToCookie(WKorbWrapper.warenkorb);
            return RedirectToAction("Produkte");
        }

        public ActionResult Impressum()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Checkout(List<WKorb.WKorbItem> wkorb)
        {
            // wenn nicht eingeloggt zuerst Login
            if (Session["authenticated"] == null || Session["authenticated"].Equals(""))
                return RedirectToAction("Index", "Login");
            var p = new PraktikumDataContext();
            var warenkorb = new WKorb(wkorb, Session["role"] != null ? Session["role"].ToString() : "");
            var zahlung = new Zahlung()
            {
                Aut_Server = "127.0.0.0.1",
                Betrag = warenkorb.GetSumme(),
                Status = 10,
                Zeitstempel = DateTime.Now
            };
            p.Zahlung.InsertOnSubmit(zahlung);
            p.SubmitChanges();

            foreach (var w in wkorb)
            {
                var kauft = new Kauft()
                {
                    Endpreis = w.Preis(warenkorb.Rolle),
                    FK_FE_Nutzer = Session["authenticated"].ToString().AsInt(),
                    FK_Produkt = w.ProduktId,
                    FK_Zahlung = zahlung.ID
                };
                p.Kauft.InsertOnSubmit(kauft);
            }
            p.SubmitChanges();
            return View("Index");
        }
    }
}

webshop/Views/Start/Details.cshtml
@using webshop.Models
@model webshop.Models.Produkt
@{
    ViewBag.Title = "Details";
}

<div class="container-fluid">
  <div class="row">
    <div class="col-md-2">
      @{
          Html.RenderPartial("_Login");
      }
      <div class="push-down">
        <a class="btn btn-default" href="@Url.Action("Register","Admin")" role="button">Registrieren</a>
      </div>
    </div>
    <!--Details-->
    <div class="col-md-10 vertical-line">
      <h3>Details für "@Model.Name"</h3>
      <!--Bild-->
      @{
          ViewBild bild = null;
          if (Model.Bild != null)
          {
            bild = new ViewBild(Model.Bild);
          }
      }
      @if (bild != null)
      {
          <img class="img-responsive img-thumbnail" src="@bild.Base64Representation" alt="@bild.Alt_Text" />
                          <span class="caption">@bild.Unterschrift</span>
      }
      else
      {
          <img class="img-responsive img-thumbnail" src="~/images/no_image.gif" alt="kein Bild" />
      }
      <p>@Model.Beschreibung</p>
      <div class="row">
        <!--Tabs-->
        <div class="col-md-8">
          <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#beschreibung" aria-controls="beschreibung" role="tab" data-toggle="tab">Beschreibung</a></li>
            <li role="presentation"><a href="#zutaten" aria-controls="zutaten" role="tab" data-toggle="tab">Zutaten</a></li>
            <li role="presentation"><a href="#bewertung" aria-controls="bewertung" role="tab" data-toggle="tab">Bewertung</a></li>
          </ul>

          <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="beschreibung">
              <p>@Model.Beschreibung</p>
            </div>
            <div role="tabpanel" class="tab-pane" id="zutaten">
              <p>Coming Soon</p>
            </div>
            <div role="tabpanel" class="tab-pane" id="bewertung">
              <form action="http://149.201.48.80/playground/postdata.php" method="post" class="form-horizontal">
                <div class="form-group">
                  <label for="bemerkung" class="col-sm-2 control-label">Bemerkung</label>
                  <div class="col-sm-10">
                    <textarea name="bemerkung" id="bemerkung" class="form-control" cols="10" rows="5"></textarea>
                  </div>
                </div>
                <div class="form-group">
                  <label for="benutzername" class="col-sm-2 control-label">Benutzername</label>
                  <div class="col-sm-10">
                    <input type="text" name="benutzer" class="form-control" id="benutzername" />
                  </div>
                </div>
                <div class="form-group">
                  <label for="inputBewertung" class="col-sm-2 control-label">Bewertung</label>
                  <div class="col-sm-10">
                    <select name="bewertung" id="inputBewertung" class="dropdowns">
                      @for (int i = 1; i < 5; i++)
                      {
                          <option>@i</option>
                      }
                    </select>
                  </div>
                </div>
                <button type="submit" class="btn btn-default">Bewertung abgeben</button>
                <input type="hidden" name="matrikelnummer" value="3084953" />
              </form>
            </div>
          </div>
        </div>

        <!--Preis-->
        @if (Model.price != -1)
        {
          using (Html.BeginForm())
          {
                @Html.AntiForgeryToken()
                <text>
                  <div class="col-md-2">
                    <h4>@Model.price</h4>
                    <div class="form-group">
                      <input type="number" name="anzahl" value="1" min="1" max="@int.MaxValue" class="form-control dropdowns"/>
                    </div>
                    <div class="form-group">
                      <input type="hidden" name="produkt_id" value="@Model.ID"/>
                      <input type="submit" value="Bestellen" class="btn btn-default"/>
                    </div>
                  </div>
                </text>
          }
        }
      </div>
    </div>
  </div>
</div>

webshop/Views/Start/Impressum.cshtml
@{
    ViewBag.Title = "Impressum";
}
<div class="container-fluid">
  <h1>Impressum</h1>
</div>
@section head {
  <meta http-equiv="refresh" content="5; URL=@Url.Action("Impressum", "Start"))">
}

webshop/Views/Start/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="container-fluid">
  <div class="row">
    <!--Bild-->
    <div class="col-md-4">
      <div class="media">
        <img class="img-responsive" src="~/images/no_image.gif" alt="kein Bild" />
      </div>
    </div>
    <!--rechte Seite-->
    <div class="col-md-8">
      <h2>e-Mensa.</h2>
      @{
        Html.RenderPartial("_LoggedIn");
      }
      <h3>Bestellen Sie Ihr Essen jetzt und geniessen Sie später</h3>
      <div class="row push-down">
        <div class="col-md-4">
          <p>Neu hier und Student?</p>
          <a href="@Url.Action("Register","Admin")" class="btn btn-default" role="button"><span class="glyphicon glyphicon-hand-right"></span> Registrieren</a>
        </div>
        <div class="col-md-4">
          <p>Wieder hungrig?</p>
          <a href="@Url.Action("Index","Login")" class="btn btn-default" role="button"><span class="glyphicon glyphicon-cutlery"></span> Anmelden</a>
        </div>
      </div>
      <div class="row push-down">
        <div class="col-md-8">
          <p>e-Mensa ist im Beta-Stadium und kann aktuell nicht für Bestellungen in einer der vielen Mensen verwendet werden</p>
        </div>
      </div>
    </div>
  </div>
</div>

webshop/Views/Start/Produkte.cshtml
@using webshop.Models
@model List<webshop.Models.LINQ.Produkt>

@{
    ViewBag.Title = "Produkte";
}

<h2>Produkte</h2>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-2">
      @{
          Html.RenderPartial("_Login");
      }
    </div>
    <!--rechte Seite-->
    <div class="col-md-10 vertical-line">
      <h3>Verfügbare Speisen (Bestseller)</h3>
      <div class="row">
        @{
            int i = 1;
            foreach (var item in Model)
            {
                <text>
                  <div class="col-md-2 text-center">
                    <div class="media">
                      @{
                          ViewBild bild = null;
                          if (item.Bild != null)
                          {
                            bild = new ViewBild(item.Bild);
                          }
                      }
                      @if (bild != null)
                      {
                          <img class="img-responsive img-thumbnail" src="@bild.Base64Representation" alt="@bild.Alt_Text" />
                          <span class="caption">@bild.Unterschrift</span>
                      }
                      else
                      {
                          <img class="img-responsive img-thumbnail" src="~/images/kein-bild.gif" alt="kein Bild" />
                      }
                    </div>
                    <p>@item.Name</p>
                    @Html.ActionLink("Details", "Details", "Start", new { id = item.ID }, null)
                  </div>
                </text>
                          if (i % 4 == 0)
                          {
                              @Html.Raw("</div>\n")
                              @Html.Raw("<div class=\"row\">\n")
                            }
                            i++;
                          }
        }
      </div>
    </div>
  </div>
</div>

webshop/Views/Start/Temp.cshtml
@model webshop.Models.WKorbItem

@{
    ViewBag.Title = "Temp";
}

<h2>Temp</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>WKorbItem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProduktId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProduktId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProduktId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProduktName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProduktName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProduktName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anzahl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Anzahl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anzahl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="AddProdukt" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

webshop/Views/Start/Test.cshtml
@model webshop.Models.Produkt

@{
    ViewBag.Title = "Test";
}

<h2>Test</h2>

<div>
    <h4>Produkt</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Beschreibung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Beschreibung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kategorie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategorie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preis)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

webshop/Views/Start/WKorb.cshtml
@model List<webshop.Models.WKorb.WKorbItem>

@{
    ViewBag.Title = "Warenkorb";
}

<h2>Warenkorb</h2>

<table class="table">
  <tr>
    <th>
      Produktname
    </th>
    <th>
      Anzahl
    </th>
    <th>
      Preis
    </th>
  </tr>
  @using (Html.BeginForm("Checkout", "Start", FormMethod.Post, new { id = "warenkorbForm" }))
  {
      @Html.EditorForModel()
      <tr>
        <td>Summe</td>
        <td></td>
        @{ var wkorb = new webshop.Models.WKorb(Model, Session["role"] != null ? Session["role"].ToString() : ""); }
        <td>
          <div class="form-group">
            @wkorb.GetSumme()
            <input type="submit" value="Bestellen" class="btn btn-default" />
          </div>
        </td>
      </tr>
            }
</table>